package net.sf.l2jdev.gameserver.config;

import net.sf.l2jdev.gameserver.config.custom.AllowedPlayerRacesConfig;
import net.sf.l2jdev.gameserver.config.custom.AutoPotionsConfig;
import net.sf.l2jdev.gameserver.config.custom.BankingConfig;
import net.sf.l2jdev.gameserver.config.custom.BossAnnouncementsConfig;
import net.sf.l2jdev.gameserver.config.custom.CaptchaConfig;
import net.sf.l2jdev.gameserver.config.custom.ChampionMonstersConfig;
import net.sf.l2jdev.gameserver.config.custom.ChatModerationConfig;
import net.sf.l2jdev.gameserver.config.custom.ClassBalanceConfig;
import net.sf.l2jdev.gameserver.config.custom.CommunityBoardConfig;
import net.sf.l2jdev.gameserver.config.custom.CustomDepositableItemsConfig;
import net.sf.l2jdev.gameserver.config.custom.CustomMailManagerConfig;
import net.sf.l2jdev.gameserver.config.custom.DelevelManagerConfig;
import net.sf.l2jdev.gameserver.config.custom.DualboxCheckConfig;
import net.sf.l2jdev.gameserver.config.custom.FactionSystemConfig;
import net.sf.l2jdev.gameserver.config.custom.FakePlayersConfig;
import net.sf.l2jdev.gameserver.config.custom.FindPvpConfig;
import net.sf.l2jdev.gameserver.config.custom.FreeMountsConfig;
import net.sf.l2jdev.gameserver.config.custom.MerchantZeroSellPriceConfig;
import net.sf.l2jdev.gameserver.config.custom.MultilingualSupportConfig;
import net.sf.l2jdev.gameserver.config.custom.NoblessMasterConfig;
import net.sf.l2jdev.gameserver.config.custom.NpcStatMultipliersConfig;
import net.sf.l2jdev.gameserver.config.custom.OfflinePlayConfig;
import net.sf.l2jdev.gameserver.config.custom.OfflineTradeConfig;
import net.sf.l2jdev.gameserver.config.custom.OnlineInfoConfig;
import net.sf.l2jdev.gameserver.config.custom.PasswordChangeConfig;
import net.sf.l2jdev.gameserver.config.custom.PremiumSystemConfig;
import net.sf.l2jdev.gameserver.config.custom.PrivateStoreRangeConfig;
import net.sf.l2jdev.gameserver.config.custom.PvpAnnounceConfig;
import net.sf.l2jdev.gameserver.config.custom.PvpRewardItemConfig;
import net.sf.l2jdev.gameserver.config.custom.PvpTitleColorConfig;
import net.sf.l2jdev.gameserver.config.custom.RandomSpawnsConfig;
import net.sf.l2jdev.gameserver.config.custom.SayuneForAllConfig;
import net.sf.l2jdev.gameserver.config.custom.SchemeBufferConfig;
import net.sf.l2jdev.gameserver.config.custom.ScreenWelcomeMessageConfig;
import net.sf.l2jdev.gameserver.config.custom.SellBuffsConfig;
import net.sf.l2jdev.gameserver.config.custom.ServerTimeConfig;
import net.sf.l2jdev.gameserver.config.custom.StartingLocationConfig;
import net.sf.l2jdev.gameserver.config.custom.StartingTitleConfig;
import net.sf.l2jdev.gameserver.config.custom.TransmogConfig;
import net.sf.l2jdev.gameserver.config.custom.WalkerBotProtectionConfig;
import net.sf.l2jdev.gameserver.config.custom.WeddingConfig;

public class ConfigLoader
{
	public static void init()
	{
		ServerConfig.load();
		AchievementBoxConfig.load();
		AdenLaboratoryConfig.load();
		AttendanceRewardsConfig.load();
		AttributeSystemConfig.load();
		DevelopmentConfig.load();
		FeatureConfig.load();
		FloodProtectorConfig.load();
		GameAssistantConfig.load();
		GeneralConfig.load();
		GeoEngineConfig.load();
		GrandBossConfig.load();
		HuntPassConfig.load();
		IdManagerConfig.load();
		MagicLampConfig.load();
		NpcConfig.load();
		OlympiadConfig.load();
		OrcFortressConfig.load();
		PlayerConfig.load();
		PrisonConfig.load();
		PvpConfig.load();
		RandomCraftConfig.load();
		RatesConfig.load();
		RelicSystemConfig.load();
		TrainingCampConfig.load();
		VipSystemConfig.load();
		WorldExchangeConfig.load();
		AllowedPlayerRacesConfig.load();
		AutoPotionsConfig.load();
		BankingConfig.load();
		BossAnnouncementsConfig.load();
		CaptchaConfig.load();
		ChampionMonstersConfig.load();
		ChatModerationConfig.load();
		ClassBalanceConfig.load();
		CommunityBoardConfig.load();
		CustomDepositableItemsConfig.load();
		CustomMailManagerConfig.load();
		DelevelManagerConfig.load();
		DualboxCheckConfig.load();
		FactionSystemConfig.load();
		FakePlayersConfig.load();
		FindPvpConfig.load();
		FreeMountsConfig.load();
		MerchantZeroSellPriceConfig.load();
		MultilingualSupportConfig.load();
		NoblessMasterConfig.load();
		NpcStatMultipliersConfig.load();
		OfflinePlayConfig.load();
		OfflineTradeConfig.load();
		OnlineInfoConfig.load();
		PasswordChangeConfig.load();
		PremiumSystemConfig.load();
		PrivateStoreRangeConfig.load();
		PvpAnnounceConfig.load();
		PvpRewardItemConfig.load();
		PvpTitleColorConfig.load();
		RandomSpawnsConfig.load();
		SayuneForAllConfig.load();
		SchemeBufferConfig.load();
		ScreenWelcomeMessageConfig.load();
		SellBuffsConfig.load();
		ServerTimeConfig.load();
		StartingLocationConfig.load();
		StartingTitleConfig.load();
		TransmogConfig.load();
		WalkerBotProtectionConfig.load();
		WeddingConfig.load();
	}
}
