# ---------------------------------------------------------------------------
# 세력 시스템 설정 (선 vs 악)
# ---------------------------------------------------------------------------

# 세력 시스템을 활성화합니다.
# 기본값: False
EnableFactionSystem = False

# 모든 플레이어의 시작 위치(좌표)입니다.
# 기본값: 85332,16199,-1252
StartingLocation = 85332,16199,-1252

# 세력 관리자 NPC가 스폰될 위치(좌표, 방향)입니다.
# 기본값: 85712,15974,-1260,26808
ManagerSpawnLocation = 85712,15974,-1260,26808

# 선(Good) 세력의 베이스 캠프 위치입니다.
# 기본값: 45306,48878,-3058
GoodBaseLocation = 45306,48878,-3058

# 악(Evil) 세력의 베이스 캠프 위치입니다.
# 기본값: -44037,-113283,-237
EvilBaseLocation = -44037,-113283,-237

# 선(Good) 팀의 명칭입니다.
# 기본값: Good
GoodTeamName = Good

# 악(Evil) 팀의 명칭입니다.
# 기본값: Evil
EvilTeamName = Evil

# 선(Good) 팀의 캐릭터 이름 색상입니다.
# 기본값: 00FF00
GoodNameColor = 00FF00

# 악(Evil) 팀의 캐릭터 이름 색상입니다.
# 기본값: 0000FF
EvilNameColor = 0000FF

# 세력 경비병을 활성화합니다.
# NPC 템플릿의 클랜(clan) 정보에 해당 세력이 지정되어 있어야 합니다.
# 기본값: True
EnableFactionGuards = True

# 사망 시, 소속 세력의 베이스 캠프에서 부활합니다.
# 기본값: True
RespawnAtFactionBase = True

# 세력을 선택하면 플레이어가 자동으로 노블레스 상태가 됩니다.
# 기본값: False
FactionAutoNobless = False

# 세력 간의 채팅을 금지합니다. (True 설정 시 세력 간 채팅 차단 활성화)
# 기본값: True
EnableFactionChat = True

# 특정 세력의 온라인 플레이어 수가 더 많을 때 해당 세력으로의 로그인을 제한합니다. (세력 균형 유지)
# 기본값: True
BalanceOnlinePlayers = True

# 온라인 플레이어 수의 최대 초과 허용 수치입니다 (위 균형 설정에 사용됨).
# 기본값: 20
BalancePlayerExceedLimit = 20