# ---------------------------------------------------------------------------
# 환영 메시지 설정
# ---------------------------------------------------------------------------

# 캐릭터 로그인 시 화면에 웰컴 메시지(화면 중앙 메시지)를 표시합니다.
# 기본값: False
ScreenWelcomeMessageEnable = False

# 기능이 활성화되었을 때 캐릭터 로그인 시 표시할 웰컴 메시지 텍스트입니다.
# ('#'을 사용하면 줄바꿈이 되지만, 메시지는 최대 2줄까지만 가능합니다)
ScreenWelcomeMessageText = Welcome to our server!

# 기능이 활성화되었을 때 캐릭터가 게임에 로그인하면 x초 동안 웰컴 메시지를 표시합니다.
ScreenWelcomeMessageTime = 10