# ---------------------------------------------------------------------------
# Custom Starting Location
# ---------------------------------------------------------------------------

# Enable custom starting location.
# Default: False
# Default: True
CustomStartingLocation = False

# Coordinates for custom starting location.
# Default: 50821, 186527, -3625 (Giran Harbor)
# Default: 82570, 146904, -3472 (기란성 마을 만물 상인 근처)
CustomStartingLocX = 82570
CustomStartingLocY = 146904
CustomStartingLocZ = -3472
