# ---------------------------------------------------------------------------
# Starting Title
# ---------------------------------------------------------------------------

# Enable starting title.
# Default: False
# Default: True
EnableStartingTitle = True

# Starting title for new players.
StartingTitle = Newbie
