# ---------------------------------------------------------------------------
# Attendance Reward Settings
# ---------------------------------------------------------------------------
# Enable daily login rewards for players.
# Rewards are set at data\AttendanceRewards.xml file.

# Enable the Attendance Reward system.
# Default: False
EnableAttendanceRewards = True

# Enable the Attendance Reward system only for Premium accounts.
# Default: False
PremiumOnlyAttendanceRewards = False

# Enable the Attendance Reward system only for Vip accounts.
# Default: False
VipOnlyAttendanceRewards = False

# 보상을 동일한 계정에서 공유할 수 있도록 설정합니다.
# 기본값: False (캐릭터가 각자의 보상을 받습니다.)
# 기본값: True (계정당 1회만 보상을 받습니다.)
AttendanceRewardsShareAccount = True

# 로그인 후 보상을 받을 수 있는 시간(분).
# Retail: 30
AttendanceRewardDelay = 30

# 플레이어가 게임에 접속하면 보상 창이 팝업됩니다.
# Default: True = 접속하면 보상 창이 팝업
# Default: False = 접속후 30분이 경과되면 보상 창이 팝업
AttendancePopupStart = False

# 로그인 후 30분이 지나서 보상이 나올 경우 보상창을 팝업으로 띄워줍니다.
# Default: False
AttendancePopupWindow = True
