package net.sf.l2jdev.loginserver.enums;

public enum LoginFailReason {
   REASON_NO_MESSAGE(0),
   REASON_SYSTEM_ERROR_LOGIN_LATER(1),
   REASON_USER_OR_PASS_WRONG(2),
   REASON_ACCESS_FAILED_TRY_AGAIN_LATER(4),
   REASON_ACCOUNT_INFO_INCORRECT_CONTACT_SUPPORT(5),
   REASON_NOT_AUTHED(6),
   REASON_ACCOUNT_IN_USE(7),
   REASON_UNDER_18_YEARS_KR(12),
   REASON_SERVER_OVERLOADED(15),
   REASON_SERVER_MAINTENANCE(16),
   REASON_TEMP_PASS_EXPIRED(17),
   REASON_GAME_TIME_EXPIRED(18),
   REASON_NO_TIME_LEFT(19),
   REASON_SYSTEM_ERROR(20),
   REASON_ACCESS_FAILED(21),
   REASON_RESTRICTED_IP(22),
   REASON_WEEK_USAGE_FINISHED(30),
   REASON_SECURITY_CARD_NUMBER_INVALID(31),
   REASON_AGE_NOT_VERIFIED_CANT_LOG_BEETWEEN_10PM_6AM(32),
   REASON_SERVER_CANNOT_BE_ACCESSED_BY_YOUR_COUPON(33),
   REASON_DUAL_BOX(35),
   REASON_INACTIVE(36),
   REASON_USER_AGREEMENT_REJECTED_ON_WEBSITE(37),
   REASON_GUARDIAN_CONSENT_REQUIRED(38),
   REASON_USER_AGREEMENT_DECLINED_OR_WITHDRAWL_REQUEST(39),
   REASON_ACCOUNT_SUSPENDED_CALL(40),
   REASON_CHANGE_PASSWORD_AND_QUIZ_ON_WEBSITE(41),
   REASON_ALREADY_LOGGED_INTO_10_ACCOUNTS(42),
   REASON_MASTER_ACCOUNT_RESTRICTED(43),
   REASON_CERTIFICATION_FAILED(46),
   REASON_TELEPHONE_CERTIFICATION_UNAVAILABLE(47),
   REASON_TELEPHONE_SIGNALS_DELAYED(48),
   REASON_CERTIFICATION_FAILED_LINE_BUSY(49),
   REASON_CERTIFICATION_SERVICE_NUMBER_EXPIRED_OR_INCORRECT(50),
   REASON_CERTIFICATION_SERVICE_CURRENTLY_BEING_CHECKED(51),
   REASON_CERTIFICATION_SERVICE_CANT_BE_USED_HEAVY_VOLUME(52),
   REASON_CERTIFICATION_SERVICE_EXPIRED_GAMEPLAY_BLOCKED(53),
   REASON_CERTIFICATION_FAILED_3_TIMES_GAMEPLAY_BLOCKED_30_MIN(54),
   REASON_CERTIFICATION_DAILY_USE_EXCEEDED(55),
   REASON_CERTIFICATION_UNDERWAY_TRY_AGAIN_LATER(56);

   private final int _code;

   private LoginFailReason(int code) {
      this._code = code;
   }

   public int getCode() {
      return this._code;
   }
}
