package net.sf.l2jdev.gameserver.network.serverpackets;

import net.sf.l2jdev.commons.network.WritableBuffer;
import net.sf.l2jdev.gameserver.model.actor.Player;
import net.sf.l2jdev.gameserver.model.actor.stat.PlayerStat;
import net.sf.l2jdev.gameserver.model.item.enums.ItemGrade;
import net.sf.l2jdev.gameserver.model.item.enums.ShotType;
import net.sf.l2jdev.gameserver.model.stats.Stat;
import net.sf.l2jdev.gameserver.model.stats.TraitType;
import net.sf.l2jdev.gameserver.network.GameClient;
import net.sf.l2jdev.gameserver.network.ServerPackets;

public class ExUserViewInfoParameter extends ServerPacket
{
	private final Player _player;

	public ExUserViewInfoParameter(Player player)
	{
		this._player = player;
	}

	@Override
	public void writeImpl(GameClient client, WritableBuffer buffer)
	{
		ServerPackets.EX_USER_VIEW_INFO_PARAMETER.writeId(this, buffer);
		PlayerStat stat = this._player.getStat();
		int index = 0;
		buffer.writeInt(185);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getPAtk());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMAtk());
		buffer.writeShort(index++);
		buffer.writeInt(!this._player.isChargedShot(ShotType.BLESSED_SOULSHOTS) && !this._player.isChargedShot(ShotType.SOULSHOTS) ? 0 : 10000 + (this._player.getActiveRubyJewel() != null ? (int) this._player.getActiveRubyJewel().getBonus() * 1000 : 0));
		buffer.writeShort(index++);
		buffer.writeInt(!this._player.isChargedShot(ShotType.BLESSED_SPIRITSHOTS) && !this._player.isChargedShot(ShotType.SPIRITSHOTS) ? 0 : 30000 + (this._player.getActiveShappireJewel() != null ? (int) this._player.getActiveShappireJewel().getBonus() * 1000 : 0));
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getActiveWeaponInstance() != null && this._player.getActiveWeaponInstance().isEnchanted() ? (int) (this._player.getActiveWeaponInstance().getEnchantLevel() * (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.S ? 1.6 : (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.A ? 1.4 : (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.B ? 0.7 : (this._player.getActiveWeaponItem().getItemGrade().equals(ItemGrade.C) ? 0.4 : (this._player.getActiveWeaponItem().getItemGrade().equals(ItemGrade.D) ? 0.4 : 0.0))))) * 100.0) : 0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getActiveWeaponInstance() != null && this._player.getActiveWeaponInstance().isEnchanted() ? (int) (this._player.getActiveWeaponInstance().getEnchantLevel() * (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.S ? 1.6 : (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.A ? 1.4 : (this._player.getActiveWeaponItem().getItemGrade() == ItemGrade.B ? 0.7 : (this._player.getActiveWeaponItem().getItemGrade().equals(ItemGrade.C) ? 0.4 : (this._player.getActiveWeaponItem().getItemGrade().equals(ItemGrade.D) ? 0.4 : 0.0))))) * 100.0) : 0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.SHOTS_BONUS, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.SHOTS_BONUS, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_PHYSICAL_ATTACK_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_PHYSICAL_SKILL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_MAGICAL_SKILL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_PHYSICAL_ATTACK_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_PHYSICAL_SKILL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_MAGICAL_SKILL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_DAMAGE_TAKEN, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PHYSICAL_SKILL_POWER, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.MAGICAL_SKILL_POWER, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.AREA_OF_EFFECT_DAMAGE_MODIFY, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SWORD) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SWORD) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SWORD) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.ANCIENTSWORD) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.DAGGER) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.RAPIER) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.BLUNT) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.BLUNT) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.BLUNT) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.BLUNT) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.POLE) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.DUALFIST) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.DUAL) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.BOW) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.PISTOLS) * 100 * 100 - 10000);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getPDef());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMDef());
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.SOULSHOT_RESISTANCE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.SPIRITSHOT_RESISTANCE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_PHYSICAL_ATTACK_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_PHYSICAL_SKILL_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_MAGICAL_SKILL_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVP_DAMAGE_TAKEN, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_PHYSICAL_ATTACK_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_PHYSICAL_SKILL_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_MAGICAL_SKILL_DEFENCE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PVE_DAMAGE_TAKEN, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.AREA_OF_EFFECT_DAMAGE_DEFENCE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SWORD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SWORD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SWORD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.ANCIENTSWORD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.DAGGER) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.RAPIER) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.BLUNT) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.BLUNT) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.BLUNT) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.BLUNT) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.POLE) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.FIST) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.DUAL) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.BOW) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.PISTOLS) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getShldDef());
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.SHIELD_DEFENCE_RATE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.MAGIC_SUCCESS_RES, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.VENGEANCE_SKILL_MAGIC_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.REAL_DAMAGE_RESIST, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.ATTACK_CANCEL, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getAccuracy());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMagicAccuracy());
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.BLOW_RATE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getEvasionRate());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMagicEvasionRate());
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.BLOW_RATE_DEFENCE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getSkillEvasionTypeValue(0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getSkillEvasionTypeValue(1) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getPAtkSpd());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getMAtkSpd());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getMoveSpeed());
		buffer.writeShort(index++);
		buffer.writeInt(stat.getCriticalHit() * 10);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getCriticalHit());
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getPSkillCriticalRate() * 10);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getPSkillCriticalRate());
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMCriticalHit() * 10);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.getMCriticalHit());
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_CRITICAL_RATE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_CRITICAL_RATE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_PHYSICAL_SKILL_CRITICAL_RATE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_PHYSICAL_SKILL_CRITICAL_RATE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_MAGIC_CRITICAL_RATE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_MAGIC_CRITICAL_RATE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.CRITICAL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getCriticalDmg(0.0));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.PHYSICAL_SKILL_CRITICAL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.PHYSICAL_SKILL_CRITICAL_DAMAGE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.MAGIC_CRITICAL_DAMAGE, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.MAGIC_CRITICAL_DAMAGE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_CRITICAL_DAMAGE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_CRITICAL_DAMAGE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_PHYSICAL_SKILL_CRITICAL_DAMAGE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_PHYSICAL_SKILL_CRITICAL_DAMAGE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.DEFENCE_MAGIC_CRITICAL_DAMAGE, 100.0) - 100.0) * 100 * -1);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.DEFENCE_MAGIC_CRITICAL_DAMAGE_ADD));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.ADDITIONAL_POTION_HP_PER, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.ADDITIONAL_POTION_HP));
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.ADDITIONAL_POTION_MP_PER, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getValue(Stat.ADDITIONAL_POTION_MP));
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getHpRegen());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(!this._player.isMoving() ? stat.getHpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isSitting() ? stat.getHpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isMoving() && !this._player.isRunning() ? stat.getHpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isRunning() ? stat.getHpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getMpRegen());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(!this._player.isMoving() ? stat.getMpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isSitting() ? stat.getMpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isMoving() && !this._player.isRunning() ? stat.getMpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isRunning() ? stat.getMpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(stat.getCpRegen());
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(!this._player.isMoving() ? stat.getCpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isSitting() ? stat.getCpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isMoving() && !this._player.isRunning() ? stat.getCpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(this._player.isRunning() ? stat.getCpRegen() : 0);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getReuseTypeValue(0) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getReuseTypeValue(1) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getReuseTypeValue(3) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getMpConsumeTypeValue(0) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getMpConsumeTypeValue(1) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getMpConsumeTypeValue(3) * 100 * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.RESIST_DISPEL_BUFF, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) (stat.getValue(Stat.RESIST_ABNORMAL_DEBUFF, 100.0) - 100.0) * 100);
		buffer.writeShort(index++);
		buffer.writeInt(0);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.PARALYZE) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SHOCK) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.KNOCKBACK) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SLEEP) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.IMPRISON) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.PULL) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.FEAR) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SILENCE) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.HOLD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.SUPPRESSION) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getAttackTrait(TraitType.INFECTION) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.PARALYZE) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SHOCK) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.KNOCKBACK) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SLEEP) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.IMPRISON) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.PULL) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.FEAR) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SLEEP) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.HOLD) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.SUPPRESSION) * 100);
		buffer.writeShort(index++);
		buffer.writeInt((int) stat.getDefenceTrait(TraitType.INFECTION) * 100);
	}
}
